Fixed typo in setup.py, fixed bug where predict fails if output direc…
thorstenwagner/cryoCARE_pip pull request #2
Opened 2022-07-11 12:32 UTC by EuanPyle

…tory already exists, added functionality to allow user to provide a list of tomograms to predict in predict_config.json

2022-07-11 12:34 UTC, EuanPyle commented
PR which fixes a couple of errors: 
added a missing comma in setup.py, 
added a line to allow users to output tomograms in a directory that already exists without error
added a few lines to allow users to provide a list of tomograms in predict_config.json rather than either specifying the directory of even/odd tomograms or providing a string for the path to one specific tomogram

2022-08-05 13:11 UTC, thorstenwagner commented
Sorry, I didnt noticed this pull request.

Could you change

```
if not os.path.exists(config['output']):
                os.makedirs(config['output'])
```
to
```
os.makedirs(config['output'], exists_ok=True)
```

2022-08-05 13:15 UTC, thorstenwagner requested changes
Perfect, just make this mino change and we can merge it :-)

2022-08-05 13:15 UTC, thorstenwagner commented on cryocare/scripts/cryoCARE_predict.py
> +            if not os.path.exists(config['output']):
Better use
```
os.makedirs(config['output'], exists_ok=True)
```

2022-08-08 10:05 UTC, thorstenwagner commented on cryocare/scripts/cryoCARE_predict.py
> +            if not os.path.exists(config['output']):
Well, I will simply change it :-)

2022-08-08 10:05 UTC, merged